### ISSUE TITLE
how to use stconvert in ik analyzed indexes?

### ISSUE THREAD

**Issue by tigerneil** [medcl/elasticsearch-analysis-stconvert#1]
Here is my setting and mapping information
```
settings index: { number_of_shards: 1 } do
    mappings do
      indexes :seq_in_nb, type: :integer
      indexes :likes_count, type: :integer
      indexes :title, analyzer: :ik
      indexes :content_without_markup, analyzer: :ik
      indexes :shared, analyzer: :keyword, type: :boolean
      indexes :locked, analyzer: :keyword, type: :boolean
    end
  end
```

the content in our setting includes traditional and simplified Chinese. Therefore we want to search terms with both traditional and simplified Chinese and we can get the same searching result.

Now under this setting, my contents are divided into two groups with respect to each Chinese words(e.g. 中國 and 中国). 

Here comes two question:
1. could I make the words with same meaning into just one keyword (e.g. the document containing "中國" or "中国" could come to the same index)
2. As I use the following query setting
```
...
{ match_phrase: {content_without_markup: { analyzer: :t2s_convert, query: keyword, slop: 10} } }
...
```
I could use "國" to search for "国", but can't use "中國" to search for "中国". Why this situation happen? It seems almost worked. But why phrase failed?

**Comment by medcl** [comment]
because ik doesn't dealing with these situation,it didn't unify the simplified and traditional Chinese characters,but it is easy to dealing with,just define a custom analyzer,such as `custom_ik_analyzer`,use type 'custom',and set `analyzer` to `ik`,and then set this custom analyzer's token filer to this plugin `stconvert ` and now you can use the new analyzer in your mapping
